services:
  client:
    container_name: lap2_paircode_client
    build: ./client
    image: paircode_client
    ports: 
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: [ "http-server" ]

  api:
    image: node:12.18.4
    working_dir: /code
    volumes:
      - type: bind
        source: ./api
        target: /code
    container_name: lap2_paircode_api
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=telegraph
      - PGHOST=db
      - PGPASSWORD=telegraph
      - PGDATABASE=posts
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    image: postgres:12.4
    container_name: lap2_paircode_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=posts
      - POSTGRES_USER=telegraph
      - POSTGRES_PASSWORD=telegraph
volumes:
  dbdata:
networks: 
  default:
    name: lap2_paircode
    working_dir: /code
    volumes:
      - type: bind
        source: ./api
        target: /code
    container_name: lap2_paircode_api
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=telegraph
      - PGHOST=db
      - PGPASSWORD=telegraph
      - PGDATABASE=posts
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    image: postgres:12.4
    container_name: lap2_paircode_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=posts
      - POSTGRES_USER=telegraph
      - POSTGRES_PASSWORD=telegraph
volumes:
  dbdata:
networks: 
  default:
    name: lap2_paircode
